version: '3.4'

services:

  db:
    image: mongo
    restart: always
    ports:
      - 9000:27017

  login_page:
    image: login_page
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000